apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiextensions.k8s.io/v1beta1","kind":"CustomResourceDefinition","metadata":{"annotations":{},"name":"tenants.steward.sap.com"},"spec":{"additionalPrinterColumns":[{"JSONPath":".status.conditions[?(@.type==\"Ready\")].status","name":"Ready","type":"string"},{"JSONPath":".status.conditions[?(@.type==\"Ready\")].reason","name":"Reason","priority":1,"type":"string"},{"JSONPath":".status.conditions[?(@.type==\"Ready\")].message","name":"Message","priority":1,"type":"string"},{"JSONPath":".status.tenantNamespaceName","description":"The name of the namespace for this tenant.","name":"Tenant-Namespace","type":"string"},{"JSONPath":".metadata.creationTimestamp","name":"Age","type":"date"}],"group":"steward.sap.com","names":{"kind":"Tenant","plural":"tenants","singular":"tenant"},"scope":"Namespaced","subresources":{"status":{}},"validation":{"openAPIV3Schema":{"required":[],"type":"object"}},"version":"v1alpha1"}}
  creationTimestamp: "2020-01-15T14:30:27Z"
  generation: 1
  name: tenants.steward.sap.com
  resourceVersion: "6648"
  selfLink: /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/tenants.steward.sap.com
  uid: 92f2544b-37a3-11ea-8108-4201ac100004
spec:
  additionalPrinterColumns:
  - JSONPath: .status.conditions[?(@.type=="Ready")].status
    name: Ready
    type: string
  - JSONPath: .status.conditions[?(@.type=="Ready")].reason
    name: Reason
    priority: 1
    type: string
  - JSONPath: .status.conditions[?(@.type=="Ready")].message
    name: Message
    priority: 1
    type: string
  - JSONPath: .status.tenantNamespaceName
    description: The name of the namespace for this tenant.
    name: Tenant-Namespace
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  conversion:
    strategy: None
  group: steward.sap.com
  names:
    kind: Tenant
    listKind: TenantList
    plural: tenants
    singular: tenant
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: Tenant
    listKind: TenantList
    plural: tenants
    singular: tenant
  conditions:
  - lastTransitionTime: "2020-01-15T14:30:27Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: null
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1alpha1
