apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1beta1","kind":"ClusterRoleBinding","metadata":{"annotations":{},"name":"steward-system"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"cluster-admin"},"subjects":[{"kind":"ServiceAccount","name":"steward-system","namespace":"steward-system"}]}
  creationTimestamp: "2020-01-15T14:30:27Z"
  name: steward-system
  resourceVersion: "6655"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterrolebindings/steward-system
  uid: 9350abd6-37a3-11ea-8108-4201ac100004
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: steward-system
  namespace: steward-system
