apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"steward-tenant-controller"},"name":"steward-tenant-metrics","namespace":"steward-system"},"spec":{"clusterIP":"None","ports":[{"name":"http-metrics","port":9090,"protocol":"TCP","targetPort":9090}],"selector":{"app":"steward-tenant-controller"},"sessionAffinity":"None","type":"ClusterIP"}}
  creationTimestamp: "2020-01-15T14:30:28Z"
  labels:
    app: steward-tenant-controller
  name: steward-tenant-metrics
  namespace: steward-system
  resourceVersion: "6684"
  selfLink: /api/v1/namespaces/steward-system/services/steward-tenant-metrics
  uid: 93ae9c4f-37a3-11ea-8108-4201ac100004
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: steward-tenant-controller
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
